language: generic # setting language to C will override cross-compiler and fail

sudo: required
dist: trusty

notifications:
  irc:
    channels:
      - "irc://irc.freenode.net:8001/#zjs"
    on_success: change
    on_failure: always

env:
  global:
    - ZEPHYR_GCC_VARIANT=zephyr
    - ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
    - ZEPHYR_BASE=$TRAVIS_BUILD_DIR/deps/zephyr
    - ZEPHYR_SDK_VERSION=0.9
    - ZEPHYR_SDK_DOWNLOAD_FOLDER=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/$ZEPHYR_SDK_VERSION
    - ZEPHYR_SDK_SETUP_BINARY=zephyr-sdk-$ZEPHYR_SDK_VERSION-setup.run
    - ZEPHYR_SDK_DOWNLOAD_URL=$ZEPHYR_SDK_DOWNLOAD_FOLDER/$ZEPHYR_SDK_SETUP_BINARY
  matrix:
    - TARGET="zephyr"
    - TARGET="extra"
    - TARGET="linux"
    - TARGET="ashell"

cache:
  directories:
    - $ZEPHYR_SDK_INSTALL_DIR

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install make gcc g++ python3-ply ncurses-dev uglifyjs libc6-dev-i386 -qq

install: >
  if [ "$TARGET" != "linux" -a "$(cat $ZEPHYR_SDK_INSTALL_DIR/sdk_version)" != "$ZEPHYR_SDK_VERSION" ]; then
    wget $ZEPHYR_SDK_DOWNLOAD_URL &&
    chmod +x $ZEPHYR_SDK_SETUP_BINARY &&
    rm -rf $ZEPHYR_SDK_INSTALL_DIR &&
    ./$ZEPHYR_SDK_SETUP_BINARY --quiet -- -y -d $ZEPHYR_SDK_INSTALL_DIR > /dev/null;
  fi

before_script: >
  source zjs-env.sh &&
  if [ "$TARGET" != "linux" ]; then
    make update &&
    source deps/zephyr/zephyr-env.sh
  fi

script: >
  trlite -l $TARGET
